name: Agent Publish

on: 
  pull_requets:
    branches:
      - main

jobs:
  Publish:
    - name: Set branch name in env var
      run: echo "BRANCH=$(echo $GITHUB_HEAD_REF | cut -d '\' -f 1)" >> $GITHUB_ENV
    - name: Create folder for private key
      run: mkdir -p ~/.forta
    - name: Create private key file
    - run: echo ${{ secrets.PRIVATE_KEY_FILE }} > ~/.forta/privateKey
    - uses: actions/checkout@v2
    - name: Install action npm packages
      run: npm install @actions/core @actions/exec
    - name: Install expect
      run: sudo apt install expect
    # - name: Publish Agent
    #   if: env.BRANCH == '@agent' && github.event.pull_request.merged == true
    #   uses:
